const Product = require('../models/Product');

const SPECIAL_ROWS_5KG = [
  ['SWEET CARESS', 'TF TOBACCO VANILLE TYPE'],
  ['BEAUTY OF ARABIA 72', 'ROSE MUSK'],
  ['ASLI GULAB', 'CREATIONS'],
  ['ATTAR PHOOL SUPER', 'CREATIONS'],
  ['BLOSSOM LC', 'GUCCI BLOOM'],
  ['MOST WANTED', 'AZZARO MOST WANTED'],
  ['GIVEX 510355', 'DARK BLACK'],
  ['GIVEX 510376', 'OPIUM'],
  ['GIVEX 54177 MX IN DE', 'POLO SPORT FOR MEN'],
  ['GIVEX 54184', 'AQUA MARINE'],
  ['GIVEX 610374', 'Polo sport for Men'],
  ['GIVEX 610398', 'Eternity for men'],
  ['GIVEX 613512', 'One million'],
  ['GIVEX 69328', 'OMBRE ROSE'],
  ['GIVEX 69352', 'AMARIGE'],
  ['GIVEX 78018', 'WHITE MUSK'],
  ['GIVEX 54099', 'BOSS GREEN'],
  ['GIVEX 67009', 'FAWAKEH'],
  ['GIVEX 59309', 'COOL WATER MEN'],
  ['GIVEX 69304', 'COOL WATER WOMEN'],
  ['GIVEX 610399', 'BRUT'],
  ['GIVEX 510378', 'HAVOC'],
  ['GIVEX 510397', 'OPEN'],
  ['GIVEX 54088', 'TOMMY TYPE'],
  ['GIVEX 54192', 'ISSE MIYAKE'],
  ['GIVEX 64202', 'CIGAR'],
  ['PAREFX 11551', 'JANNAT EL FIRDAUS'],
];

const SPECIAL_ROWS_25KG = [
  ['NIGHT VISION', 'SPICE BOMB BY AZZARO'],
  ['SPIRIT FUMES', 'INVICTUS BY PACO ROBBANE'],
  ['FUSION MANIA', 'BOMBSHELL BY VICTORIA SECRATE'],
  ['DEEP DESIRE', 'CHANEL NO.5'],
  ['ETERNAL MERMAID', 'CK Eternity Women'],
  ['COOL VIBES', 'Cool water'],
  ['WHITE OUD', 'WHITE OUD'],
  ['SUMMER SHIMMER EXCE INDE', 'ALLURE DE HOMME'],
  ['JOYFUL REFRESH', 'D&G The One'],
  ['POWER HOUSE', 'Creed silver Mountain'],
  ['INFINITE NIGHTS', 'OUD ROYAL - AGAR'],
  ['INSTANT FRESHNESS', 'Guerlain Instant Type'],
  ['EARTH HOUR 57', 'TERRE DE HERMES'],
  ['MACHO HERO', 'MCNROE SPARK'],
  ['BLACK BLOOM 74', 'Black Opium'],
  ['PASSION BOMB', 'Victoria secrets Flower bomb'],
  ['FLORAL TWIST', 'Miss Chloe with escada twist'],
  ['ADORABLE BLOOMS', "J'Adore"],
  ['DAYBREAK', 'Eros Versace'],
  ['NIGHT BLOOM', 'Tresor Midnight rose'],
  ['SPACE CULT', 'ALIEN MUGLER'],
  ['ORIENTAL LOVE', 'Bacarrat Rouge 540'],
  ['SALVATION ARMY', 'DIOR SAVAGE'],
  ['BLACK GARDEN', 'Black opium'],
  ['BLACK INTENSE', 'BLACK OPIUM'],
  ['CLASSIC SAFARI', 'SAFARI BY RALF LAURENT'],
  ['OCEAN COOL', 'DAVIDOFF - COOL WATER'],
  ['ROUGH LIGHT', 'Rose Bulgaria'],
  ['GIVEX 59312', 'DRAKKAR : FOUGERE'],
  ['ROSE AURA', "Di'or Rose"],
  ['SURF MAN', 'Acqua Di Gio men'],
  ['GUILTY GECKO', 'Gucci Guilty - Absolute Pour Femme'],
  ['GIVEX - 611433', 'BLEU RASSI MEN'],
  ['GIVEX 79331', 'floral fruity oriental'],
  ['ORCHID VELVET', 'TOM FORD BLACK ORCHID'],
  ['Blue Current', 'BVLGARI-AQVA M05'],
  ['DELTA PINK', 'Delina exclusive'],
  ['DESIRE MAROON', 'DUNHILL DESIRE FOR HIM'],
  ['GIVEX 54177 MX INDE', 'POLO SPORT FOR MEN'],
  ['Givex 54099', 'Hugo boss'],
  ['VANILLA WRAP', 'KayAli Utopia Vanilla Coco'],
  ['GIVEX 611436', 'GUCCI GUILTY'],
  ['PARISIAN INSTANT', "Guerlain Paris - L'instant Magic"],
  ['FREEDOM GIRL', 'LIBRE YSL'],
  ['MUSK HEAVEN', 'White musk type'],
  ['ARABIC NIGHT', 'Tuscan Leather'],
  ['ISAKA', 'Issey miyake'],
  ['ALLURING OUD', 'Oud Al Layal'],
  ['ARABIC DIVINE', 'SIMPLY OUD LATAFA'],
  ['PINK SPLASH', 'VICTORIA SECRET-SCANDALOUS'],
  ['BRIGHT LIGHT', 'OMBRE NOMADE'],
  ['MALE ALLURE', 'Givenchy Gentlemen'],
  ['RIDING GLORY', 'L. VUITTON - STELLAR TIMES'],
  ['FAMOUS LADY', 'GOOD GIRL GONE BAD BY KILIAN'],
  ['ANGEL WINGS', 'Angel Mugler EDP'],
  ['MOUNTAIN TOP', 'HUGO BY HUGO BOSS'],
  ['SECRET ADMIRER', 'VICTORIA SECRET BOMBSHELL'],
  ['AQUATIC BREEZE', 'BVLGARI-AQVA POUR HOMME'],
  ['Faith Avenue', 'Creed Aventus'],
  ['PARISIAN POLE', 'Orto parisi : Megamare'],
  ['CLASSIC WAND', "PENHALIGON'S INIMITABLE WILLIA"],
  ['LOUD ROAR', 'ROARING RADCLIFF BY PENHALIGON'],
  ['MIDNIGHT FORGE LC', 'H.BOSS-THE SCENT ELIXIR M24'],
  ['IRISH NOBLE LC', 'CREED-ABSOLU AVENTUS M23'],
  ['DEEP SURF LC', 'RADA LUNA ROSSA OCEAN LE PARFUM M2'],
  ['VICTORIOUS SUMMIT LC', 'P.RABANNE-INVICTUS PARFUM M24'],
  ['MIDNIGHT SUEDE 15', 'V&R- SPICEBOMB DARK LEATHER M24'],
  ['BOLD LOVE', 'MUGLER ALIEN MEN'],
  ['AGAR OUD', 'TF OUD WOOD'],
  ['HIPPIE WORLD', 'BYREDO GYPSY WATER'],
  ['GUILTY ME', 'GUCCI GUILTY'],
  ['GUILTY YOU', 'GUCCI GUILTY'],
  ['NIGHT BLIZZARD', 'D&G LIGHT BLUE'],
  ['ROYAL ELEGANCE', 'MUSK RIZALI'],
  ['SANDAL PRIDE', 'LE LABO SANTAL 33'],
  ['CODED ARMOUR LC', 'HUGO BOSS BOTTLED ABSOLU M24'],
  ['TITAN GLORY LC', 'BURBURRY HERP PARFUME M24'],
  ['CEDAR EMBRACE LC', 'H. BOSS BOTTLED TRIUMPH ELIXER M24'],
  ['MID NIGHT FORGE LC', 'H. BOSS THE SCENT ELIXIER'],
  ['INTENSE WARRIOR LC', 'P.RABANNE-PHANTOM INTENSE M24'],
  ['IRON MAVERICK LC', 'Givenchy Gentlemen SOCIETY EXTREME M2'],
  ['SAVAGE HORIZON LC', 'D&G K DEEP INTENSE M24'],
  ['CORAL SERAPHINA 08', "BORN TO STAND OUT-ANGEL'S POWER"],
  ['NIGHT GLEAM', 'FERDRIC MALLE- THE NIGHT'],
  ['ROSE ALLURE', "MFK- L'HOMME A LA ROSE EDP MEN"],
  ['ETERNAL JARDIN', "DIOR J'ADORE FOR WOMEN"],
  ['ETHEREAL SERENADE 47', 'LV LOVERS U 24'],
  ['INVASION ONSET', 'XERJOFF-ALEXANDRIA II'],
  ['MADAM ELEGANCE', 'CHANEL COCO MADEMISELLE WOMEN'],
  ['MOLTEN WOODS 98', 'N RODRIGUES FOR HIM VETIVER MUSC'],
  ['WILD HOBBY', 'POLO BY RALPH LAUREN COLONGE'],
  ['BEACH SWIM', 'LV AFTERNOON SWIM'],
  ['PEACEFULL CAPTURE 67', 'ROJA DOVE ENIGMA FEMME F 13'],
  ['PRISTINE GALAXY 50', 'ROJA DOVE ENIGMA FEMME F 13'],
  ['SPECIAL SERVICE', 'LATAFFA FAKAHAR'],
  ['JOYOUS CHARM', 'VERSACE POUR HOMME EDT'],
  ['PINK SKY', 'LATAFFA YARA'],
  ['SPORT EXTREME', 'CHANEL ALLURE HOMME SPORTS MEN'],
  ['FREE FALL', 'YSL- LIBRE'],
  ['LUSCIOUS PEONY', 'CREATION'],
  ['SAHARA ESSENCE', 'CREATION'],
  ['GIVEX 65031 MX INDE', 'CHANEL COCO MADEMOISELLE'],
  ['GREATER HEIGHT', 'GABRIAL CHANEL'],
  ['ONE DREAM', 'D & G THE ONE'],
  ['SPARKLING GARDEN', 'KKW CRYSTAL GARDENIA'],
  ['SAKINA', 'WHITE OUD'],
  ['EGO ESSENCE', 'EGOISTE PLATINUM CHANEL'],
  ['ARMOUR SHIELD', 'ERJOFF- VERBA PURA UNISEX 19'],
  ['Y AXIS', 'XERJOFF NAXOS EDP UNISEX 2015'],
  ['WINNING APPLAUD', 'INVICTUS BY PACO ROBBANE'],
  ['BLUE WAVES', 'BVLGARI AQVA'],
  ['SALVATION KNIGHT', 'DIOR SAUVAGE'],
  ['VELVET ROSE 56', 'ROSES VANILLE'],
  ['BEAUTY OF ARABIA 72', 'ROSE MUSK'],
  ['OUD DESIRE 55', 'NUR SO OUD TYPE'],
  ['ESSENCE D OR', 'GOLDEN DUST TYPE'],
  ['FLORAL CROWN', 'SUPREME BOUQUET TYPE'],
  ['DARK DRIVE', 'DRAKKER NOIR'],
  ['WHITE SUN', 'CREATIONS'],
  ['WHITE STALLION', 'CREATIONS'],
  ['CHERRY MIST', 'CREATIONS'],
  ['DARK PECK', 'CREATIONS'],
  ['GARDENIA DREAMS', 'CREATIONS'],
  ['MIMOSA FUN', 'CREATIONS'],
  ['BRIGHT LIGHTS', 'CREATIONS'],
  ['ORCHID BLOOM', 'CREATIONS'],
  ['CHERRY FRESH', 'CREATIONS'],
  ['VANILLA LOVE', 'CREATIONS'],
  ['PRECIOUS GOLD', 'SANDAL GOLD'],
  ['HAMDAM', 'CREATIONS'],
  ['JAZIIRA', 'CREATIONS'],
  ['DASTAK', 'CREATIONS'],
  ['IQRAAR', 'CREATIONS'],
  ['MURAD', 'CREATIONS'],
  ['BLUE KNIGHT', 'CREATIONS'],
  ['BLACK PEARL', 'CREATIONS'],
  ['SUPRANO', 'CREATIONS'],
  ['MACHO AWE', 'CREATIONS'],
  ['WHITE CREST', 'CREATIONS'],
  ['ARABIAN OUD IN', 'FINE FRAGRANCE'],
  ['AVATAR LF INDE', 'POISON TYPE'],
  ['BASE GCG', 'GUCCI GUILTY'],
  ['BASE RBM', 'CREATION FINE FRAGRANCE'],
  ['BOUQUET BLOOM', 'YSL SUPREME BOUQUET'],
  ['COOL VIBES', 'COOL WATER'],
  ['CORAL INDE', 'MULTI PURPOSE'],
  ['DHAVANA', 'MULTI USE'],
  ["ESSENCE D' OR 57", 'GOLDEN DUST TYPE'],
  ['FLEUR KISS', 'FINE FRAGRANCE'],
  ['FOREVER LIME', 'MULTI PURPOSE'],
  ['FWC 1028 ORANGE', 'MULTI PURPOSE'],
  ['GREEN TALES', 'DIOR SAUVAGE TYPE'],
  ['HYDRO ROSE INDE', 'ROSE'],
  ['LAVENDER GARDEN INDE', 'MULTI PURPOSE'],
  ['LIME BURST', 'MULTI PURPOSE'],
  ['LUXURY PINK', 'MULTI PURPOSE'],
  ['MORNING JASMINE', 'MULTI PURPOSE'],
  ['PUSHPA (MOGRA)', 'MULTI PURPOSE'],
  ['RENA A 102.241', 'MULTI PURPOSE'],
  ['RICH PEACH', 'MULTI PURPOSE'],
  ['ROSE AGRA 9624', 'MULTI PURPOSE'],
  ['ROSE IVY INDE', 'MULTI PURPOSE'],
  ['SHOW MAN', 'ONE MAN SHOW'],
  ['SPARKLING GARDEN (25kg)', 'KKW CRYSTAL GARDENIA'],
  ['SPICY HUES (25k)', 'FINE FRAGRANCE'],
  ['STASHIA INDE (10kg)', 'MULTI PURPOSE'],
  ['SUNNY LEMON (25kg)', 'MULTI PURPOSE'],
  ['SWEET CARESS', 'TF TOBACCO VANILLE TYPE'],
  ['TOM OUD (25 Kg)', 'TF OUD WOOD'],
];

const SPECIAL_ROWS = [
  ...SPECIAL_ROWS_5KG.map(([firstColumn, secondColumn]) => [firstColumn, secondColumn, 5]),
  ...SPECIAL_ROWS_25KG.map(([firstColumn, secondColumn]) => [firstColumn, secondColumn, 25]),
];

const toSku = (firstColumn, weightKg) => `GIVEX${Number(weightKg)}KG${String(firstColumn || '').trim()}`;
const toName = (firstColumn, secondColumn, weightKg) => {
  const baseName = secondColumn;
  return `${String(baseName || '').trim()} ${Number(weightKg)} KG ESSENTIAL OIL`;
};

const buildSpecialPayload = (firstColumn, secondColumn, weightKg) => ({
  name: toName(firstColumn, secondColumn, weightKg),
  sku: toSku(firstColumn, weightKg),
  description: 'Price on enquiry. Click GET BEST PRICE to request a callback.',
  price: 0,
  enquiryOnly: true,
  stock: 0,
  weightKg: Number(weightKg),
  category: 'essential-oils',
  categories: ['essential-oils', 'all'],
  images: [],
  isActive: true,
});

const upsertSpecialEnquiryProducts = async () => {
  let created = 0;
  let updated = 0;

  for (const [firstColumn, secondColumn, weightKg] of SPECIAL_ROWS) {
    const payload = buildSpecialPayload(firstColumn, secondColumn, weightKg);
    const existing = await Product.findOne({ sku: payload.sku });
    if (!existing) {
      await Product.create(payload);
      created += 1;
    } else {
      Object.assign(existing, payload);
      await existing.save();
      updated += 1;
    }
  }

  return { created, updated, total: SPECIAL_ROWS.length };
};

module.exports = {
  SPECIAL_ROWS,
  upsertSpecialEnquiryProducts,
};
